multi-pane access, finally. super exciting

diff --git a/sidechat/sidechat b/sidechat/sidechat
--- a/sidechat/sidechat
+++ b/sidechat/sidechat
@@ -65,7 +65,7 @@ help() {
     system_prompt
   fi
   cat <<END
-  /choose   - Switch pane capture focus.
+  /choose   - Switch pane capture focus. (current: ${pane_list[@]})
   /clip     - Select text into the clipboard as context.
   /mindwipe - Forget this crazy world and start over.
   /model    - Switch model.
@@ -115,10 +115,12 @@ update() {
 }
 
 flash() {
-    if [[ -n "$TMUX" && -n "$pane_id" ]]; then
-        tmux select-pane -t $pane_id -P 'bg=colour95'; sleep 0.03
-        tmux select-pane -t $pane_id -P 'bg=color129'; sleep 0.03
-        tmux select-pane -t $pane_id -P 'bg=default' 
+    if [[ -n "$TMUX" ]]; then
+        for ix_pane in "${pane_list[@]}"; do
+            tmux select-pane -t $ix_pane -P 'bg=colour95'; sleep 0.03
+            tmux select-pane -t $ix_pane -P 'bg=color129'; sleep 0.03
+            tmux select-pane -t $ix_pane -P 'bg=default' 
+        done
         tmux select-pane -t $my_id
     fi
     set_prompt
@@ -170,6 +172,8 @@ set_prompt() {
 
 choose() {
     local depth=${1:-0}
+    eval 'declare -A _pane_mapping=( '$(tmux list-panes -a -F "[#{pane_id}]=#{pane_index}" | tr '\n' ' ')' )'
+    [[ "$depth" == 0 ]] && echo "Select panes or any other key to end selection" | $MDREAD
     [[ -z "$TMUX" ]] && return
     tmux display-panes -d 0 "run-shell 'echo %% > $MDIR/pane-id'"
     if [[ $? == "1" ]] ; then
@@ -181,21 +185,31 @@ choose() {
         [[ "$depth" == 0 ]] && pane_list=( )
         pane_list+=( $pane_id )
         (( depth ++ ))
-        echo "Using $pane_id"
+        {
+            echo -n "* [ "
+            for _ix in "${pane_list[@]}"; do
+                echo -n " ${_pane_mapping[$_ix]}"
+            done
+            echo -n " ]"
+        } | $MDREAD
         flash
         rm "$MDIR/pane-id"
         tmux select-pane -t $my_id
-        touch "$MDIR/${paneid}.{convo,old}"
-        INJECT=" (Note: User changed focus to a new tmux pane)"
+        touch "$MDIR/${pane_id}."{convo,old}
+        INJECT=" (Note: User changed tmux panes)"
 
         # If you're choosing something you probably also want to capture
         # I had forgotten the flow and was running choose a few times 
         # wondering why it wasn't capturing
-        [[ "$CAPTURE" == "OFF" ]] && capture
+        choose "$depth"
     else
-        [[ "$depth" == "0" ]] && echo "Cancelled" || echo "Done"
+        [[ "$depth" == "0" ]] && echo "Cancelled" 
         return 1
     fi
+    if [[ "$CAPTURE" == "OFF" ]]; then
+        capture
+    fi
+    read -t 0.05 -n 1
     return 0
 }
 
@@ -365,9 +379,7 @@ clip() {
 
     if [[ -n "$USECLIP" ]]; then
         {
-            echo
-            echo "Found!"
-            echo "### Next prompt will use \`$USECLIP\`"
+            echo -e "\nFound!\n### Next prompt will use \`$USECLIP\`"
         } | $MDREAD
     else
         echo "Aborted"
@@ -397,9 +409,16 @@ fi
 flash
 
 emit_capture() {
-    echo "<capture-pane -p>"
-    cat "$MDIR/${pane_id}.new"
-    echo -n "</capture-pane -p>"
+    local ix=$1
+    echo " has_changed=True>"
+    [[ -n "$TMUX" ]] && _pid=$(tmux display -pt "$ix" '#{pane_pid}')
+
+    if [[ "$(uname)" == "Linux" && -n "$TMUX" ]]; then
+        echo "<ps hierarchy>$(ps -o comm= --ppid $_pid -p $_pid | tr '\n' ' ')</ps hierarchy>"
+    fi
+    echo "<capture>"
+    cat "$MDIR/${ix}.new"
+    echo "</capture>"
 }
 
 while [ 0 ]; do 
@@ -459,19 +478,12 @@ while [ 0 ]; do
     # synchronize input & output
     if [[ -z "$RETRY" ]]; then
         { echo -e "\n\n"; echo "$conv_id:${_uuid}"; } | tee -a "$MDIR/input.txt" | cat >> "$MDIR/output.txt"
-        echo "($text)" >> "$MDIR/input.txt"
     fi
 
     if [[ -z "$USECLIP" && $CAPTURE == "ON" && -n "$TMUX" ]]; then
-        while ! tmux capture-pane -t "${pane_id}" -p > "$MDIR/${pane_id}.new"; do
-            echo "Choose another pane"
-            choose
-            if [[ $? == 1 ]]; then 
-                echo "Ok fine, no capture, that's fine."
-                capture
-                set_prompt
-                break
-            fi
+        for ix_pane in "${pane_list[@]}"; do
+          tmux capture-pane -t "${ix_pane}" -p > "$MDIR/${ix_pane}.new"
+          [[ -s "$MDIR/${ix_pane}.new" ]] || echo "**WARNING: Can't capture ${ix_pane}, Use /choose to update**" | $MDREAD
         done
     fi
     
@@ -479,33 +491,31 @@ while [ 0 ]; do
     in="$MDIR/${conv_id}_${_uuid}"
     {
        if [[ -n "$USECLIP" ]]; then
+           echo "<clipboard>"
            $USECLIP
+           echo "</clipboard>"
        elif [[ "$CAPTURE" == "ON" ]]; then
-           [[ -n "$TMUX" ]] && _pid=$(tmux display -pt "$pane_id" '#{pane_pid}')
-           {
-                if [[ "$(uname)" == "Linux" && -n "$TMUX" ]]; then
-                    echo "<ps hierarchy>$(ps -o comm= --ppid $_pid -p $_pid | tr '\n' ' ')</ps hierarchy>"
-                fi
-
-                if [[ -n "$RETRY" ]]; then
-                    cat "$MDIR/${pane_id}.old"
-                    RETRY=
-                elif [[ -n "$forcecapture" ]]; then
-                    emit_capture
+         for ix_pane in "${pane_list[@]}"; do
+            echo -n "<pane id=$ix_pane"
+            if [[ -n "$RETRY" ]]; then
+                cp "$MDIR/${ix_pane}.old" "$MDIR/${ix_pane}.new"
+                emit_capture "$ix_pane"
+            elif [[ -n "$forcecapture" ]]; then
+                emit_capture "$ix_pane"
+            else
+                if [[ -e "$MDIR/${ix_pane}.old" ]]; then
+                    /usr/bin/diff "$MDIR/${ix_pane}.new" "$MDIR/${ix_pane}.old" > /dev/null && echo -n " has_changed=False>" || emit_capture "$ix_pane"
                 else
-                   if [[ -e "$MDIR/${pane_id}.old" ]]; then
-                        diff "$MDIR/${pane_id}.new" "$MDIR/${pane_id}.old" > /dev/null \
-                            && echo \ || emit_capture 
-                   else
-                        emit_capture
-                   fi
-                   cp "$MDIR/${pane_id}.new" "$MDIR/${pane_id}.old"
+                    emit_capture "$ix_pane"
                 fi
-           } | grep -Ev "^$"         \
-             | tee -a "$MDIR/input.txt"
+                cp "$MDIR/${ix_pane}.new" "$MDIR/${ix_pane}.old"
+            fi
+            echo "</pane>"
+         done
+         RETRY=
       fi
-
-    } | llm -m "$LLM_MODEL" "<user-query timestamp="$(date -Iseconds)">${text}${INJECT}</user-query>" -s "$SYSTEM" $ata $conv \
+    } | tee -a "$MDIR/input.txt" \
+      | llm -m "$LLM_MODEL" "<user-query timestamp="$(date -Iseconds)">${text}${INJECT}</user-query>" -s "$SYSTEM" $ata $conv \
       | tee "${in}.${n}" | tee "$MDIR/output.txt" \
       | $MDREAD -c <(echo -e "[style]\nMargin = 4")
 
